[build]
  base = "frontend"
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  VITE_API_BASE_URL = "https://chillconnect-production.up.railway.app/api"
  VITE_NODE_ENV = "production"
  VITE_SOCKET_URL = "https://chillconnect-production.up.railway.app"

# Redirects for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to backend (will need to be updated with actual backend URL)
[[redirects]]
  from = "/api/*"
  to = "https://chillconnect-production.up.railway.app/api/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; worker-src 'self' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https: https://fonts.gstatic.com; connect-src 'self' wss: https:;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"