[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = ['cd backend && npm install']

[phases.build]  
cmds = ['cd backend && npx prisma generate']

[start]
cmd = 'cd backend && node railway-start.js'